### ISSUE TITLE
Ошибка отображения вертикальной скорости в М/С

### ISSUE THREAD

**Issue by DEMONmachine** [night-ghost/minimosd-extra#134]
Когда в настройщике переключил отображение вертикальной скорости с М/М на М/С стало отображаться это

![iskh-h4cb9a](https://cloud.githubusercontent.com/assets/18690137/14838267/f5e3ca52-0c1f-11e6-8422-17523192716d.jpg)

**Comment by night-ghost** [comment]
fixed in v832
