### ISSUE TITLE
OSD restarts/blanks out on disarming the copter

### ISSUE THREAD

**Issue by ivanskj** [night-ghost/minimosd-extra#135]
When disarming after a flight the OSD reboots, and effectively zeroing out meassured mAh, tested on 824. Any other info i can provide to this issue?

**Comment by zach030801505** [comment]
I'm having the same problem, I'm just glad it's not happening in flight

**Comment by tops4u** [comment]
Same issue here. Either it states "No Data" or just blanks after quickly showing the Resumee. Using 827 with PX4 Stack.

**Comment by thecodingfrog** [comment]
Same issue, I'm using only 1 screen. What about you guys ?

**Comment by tops4u** [comment]
Tried latest (832) and same - it suddenly blanks out. I have only one Screen, no switching, not battery Attached, PAL.

**Comment by thecodingfrog** [comment]
OK, I have tested with 4 screens and it works, so bug is happening when number of screens is lower

**Comment by eiswuerfel** [comment]
Same for me. How did you set 4 screens? I uploaded all 4 tabs, but still the same.

**Comment by thecodingfrog** [comment]
You have to set to 4 screen in config tab

**Comment by tschoffy** [comment]
Same issue here though set to 4 screens in the config tab. Not happen allways when disarming but sometimes.
Any other idea someone to get rid of this Problem?

**Comment by thecodingfrog** [comment]
Works fine using 824

Le 10 mai 2016 19:03, tschoffy <notifications@github.com> a écrit :

Same issue here though set to 4 screens in the config tab. Not happen allways when disarming but sometimes.
Any other idea someone to get rid of this Problem?

**Comment by night-ghost** [comment]
fixed in v834
