### ISSUE TITLE
No input data v. 839

### ISSUE THREAD

**Issue by DrBraXo** [night-ghost/minimosd-extra#137]
На версиях 837, 838 minimosd работает в штатном режиме, при обновлении до версии 839 данные телеметрии перестают отображаться.
При старте minimosd сначала на пару секунд появляется нужная страница, затем надпись no input data.

Pixhawk, arducopter 3.3.3.

Если нужна какая-то инфа для дебага, сообщу дополнительно.

**Comment by tops4u** [comment]
According to Google Translate this means that OSD Data is not read correctly after a few secs with Version 839. I had the same Problem, why I "downgraded" to 836 which worked for me with the very same setup. 839 just showed "No Data". 

AUAV-X2, PX4 Daily Build from 21.5.16

**Comment by miferpa** [comment]
Same is happening to me, I downgrade to v383 and works fine. On test bench I get a funny sign on vertical speed, I'l test it in flight to see what happen.

**Comment by night-ghost** [comment]
fixed
