### ISSUE TITLE
Smaller font?

### ISSUE THREAD

**Issue by MacPiston** [night-ghost/minimosd-extra#145]
When original minimOSD firmware was on top, there were .mcm files with smaller fonts. Today I was searching, and found one that almost works properly with nightghost FW. Only thing I saw is that artificial horizon is bugged - idk if something else, because im not using it. Please look at the file (change extension to .mcm instead of zip)
[MinimOSD_2.4.0.2.zip](https://github.com/night-ghost/minimosd-extra/files/310375/MinimOSD_2.4.0.2.zip)
 and think about it. Cheers!
EDIT: I'm currently work'in on it, so I'll write when I'll finish.

**Comment by night-ghost** [comment]
This is good but current MCM wizard don't allows to copy characters from one font to another so it needs to redraw a lot of chars. Don't forget to change font version in PR

**Comment by MacPiston** [comment]
Yeah I have already redrawn them, but they don't want to be uploaded on
minim... I'll find them on PC and send redrawn file to you.

wt., 21.06.2016 o 08:28 użytkownik night-ghost <notifications@github.com>
napisał:

**Comment by night-ghost** [comment]
more than year, so close
