### ISSUE TITLE
Not working with Runcam Skyplus

### ISSUE THREAD

**Issue by Elerium2** [night-ghost/minimosd-extra#151]
Hello,
I have been trying to test minimosd with runcam skyplus, but the overlay doesn't appear.
If I unplug the camera, the image stays black, until I reset minimosd. After reset, the overlay appears normally.
However, with the camera, only the camera's image appear, without the overlay.
Can you help?

Note: I am using APM as flight controller

**Comment by niko919** [comment]
U can try to use manual video mode (NTSC or PAL) instead of auto.

**Comment by night-ghost** [comment]
Some Sony chips generates video that violates standard so MAX7456 can't work with such cameras. However I hasn't runcam skyplus so can't debug this issue
