### ISSUE TITLE
bearing panel

### ISSUE THREAD

**Issue by sunzhenyu19801120** [night-ghost/minimosd-extra#153]
we already have the panel "Home Direction Arrow", which is the Home direction relative to the plane. 
But, could you add a new panel "Bearing", so we can easily see the absolute bearing of the plane?
This way, we can easily know where is the plane right now relative to Home.

**Comment by night-ghost** [comment]
there is RADAR for this. It is impossible to make arrow you want because OSD don't knows where one turned his face right now.
