### ISSUE TITLE
Battery b a13 pin

### ISSUE THREAD

**Issue by triolus** [night-ghost/minimosd-extra#154]
On Mission Planner for pixhawk, a second battery read for voltage is available. It was placed on pin a13. Can this be added on battery b?

**Comment by night-ghost** [comment]
Does it data sended via MAVlink?

**Comment by triolus** [comment]
Checking. Will merge info when answered. BTW, tried to implement on battery 2 and it rolls from 0 to 16 volts. Does that mean the signal is active on battery 2 and needs correcting? Just checking.

**Comment by night-ghost** [comment]
found. there is new message BATTERY2 with code 181. Will be in next release

**Comment by triolus** [comment]
Ok thanks:)

**Comment by night-ghost** [comment]
new version 884 ready for testing - I hasn't such hardware

**Comment by triolus** [comment]
Pixhawk 2 wont shipped be until the 28th. Will be submitting for one on the 16th.
