### ISSUE TITLE
Home distance not correct

### ISSUE THREAD

**Issue by 0n3-70uch** [night-ghost/minimosd-extra#155]
Hello,

I found a little bug in Mavlink Copter Version 881. When I start my drone, fly a round and Land then the distance is shown correct. After that I picked up my drone without removing the battery and Start at another Position. Now the osd Show me the Position to the First startpoint (for example 1500m).

That's all... Everythink Else works great Thank you.
Greetings
Fabi

**Comment by night-ghost** [comment]
this was a feature - home location fixed on 1st arming only to exclude a possibility to get wrong home point in flight. 

But... I can reset home lock on disarm :)

**Comment by 0n3-70uch** [comment]
Haha ok. "This is no bug this is a feauture" ;).

But when I disarm and rearm then the distance is also shown incorrect...

**Comment by night-ghost** [comment]
You should disconnect battery when move to a new location.

**Comment by 0n3-70uch** [comment]
Thanks for the new option.
