### ISSUE TITLE
Request for 50% battery warning

### ISSUE THREAD

**Issue by Ansarida** [night-ghost/minimosd-extra#158]
Hi Night_Ghost

if u can make 50% battery warning appear in 20Sec?

**Comment by night-ghost** [comment]
I think this is not a good idea because batteries can be different and tend to deteriorate over time, lose capacity.

**Comment by Ansarida** [comment]
Yes Sir

It also can used to warning long range user to turn back... Hope it can adjustable
have ppl turn back at 60% 55% just 20sec enough to warn user to turn back

**Comment by Ansarida** [comment]
hi sir any progress on this?

**Comment by night-ghost** [comment]
I fundamentally disagree with this feature so it will not be done.

**Comment by Ansarida** [comment]
Ok Sir

Thank u
