### ISSUE TITLE
mavlink_msg_global_position_int_get_vx()

### ISSUE THREAD

**Issue by marianovolarik** [night-ghost/minimosd-extra#160]
In [read_mavlink() (MAVLink.h:357)](https://github.com/night-ghost/minimosd-extra/blob/master/MinimOsd_Extra/protocols/MAVLink.h#L357):
```
int16_t vx = mavlink_msg_global_position_int_get_vx(&msg.m); // speed for non-GPS setups
int16_t vy = mavlink_msg_global_position_int_get_vx(&msg.m);
```
should the second call be `int16_t vy = mavlink_msg_global_position_int_get_vy(&msg.m);` not `_vx`?

**Comment by night-ghost** [comment]
yes thanks, fixed
