### ISSUE TITLE
""No input data" message on the monitor from Minimosd board running under FW V889

### ISSUE THREAD

**Issue by sergeykorn** [night-ghost/minimosd-extra#162]
Though it's not a bug report..... )

Minimosd board connected to Telemetry2 port on PIXHAWK Flight controller gives "No input data" message. After pushing the reset button on the board, the screen updates and shows relevant content for a second or so and then goes back to the "No input data" message.

![image](https://cloud.githubusercontent.com/assets/22900995/19581853/395f6958-96fe-11e6-9e49-a529a7682833.png)

**Comment by sergeykorn** [comment]
I've just found that if I transmit data through COM port in Config_OSD tool the screen goes as it supposed to be. As soon as the transmission is stopped No Input data message pops up again!

**Comment by night-ghost** [comment]
>As soon as the transmission is stopped No Input data message pops up again!

you must be joking! YES if transmission is stopped OSD REALLY hasn't any input data

**Comment by sergeykorn** [comment]
I meant a transmission goes through while OSD board is connected to PC via USB to TTL adapter. It's giving the same No Input Data msg when connected to Pixhawk telemetry port anyway! Why it's not showing the screen set up in configuration tool with the chosen graphics and zero values for variable parameters if actually there is no input data?!

**Comment by mP1** [comment]
@sergeykorn 

Im having basically the same problem, and found a solution. I no my setup was correct as sometimes the "no mavlink data" screen would show my gps coords. After i did change my params as shown below the osd just worked ;)

Issue 121 (here) has the solution.

> you have to disable either BRD_SER1_RTSCTS or BRD_SER2_RTSCTS by setting it to 
0 (or maybe both). 

https://github.com/night-ghost/minimosd-extra/issues/121

Hope that helps...

**Comment by sergeykorn** [comment]
Thanks, I will try these settings.

**Comment by sergeykorn** [comment]
Doesn't help :(

**Comment by Zethyl** [comment]
worked for me on Plane 3.8.2 with minimosd-extra MAVLINK934DV
