### ISSUE TITLE
Battery voltage from BattB pin resetting every 2-3 seconds

### ISSUE THREAD

**Issue by hackra76** [night-ghost/minimosd-extra#163]
Hi, on latest v892DV-Mavlink I have inconsistent battery voltage reading. It keeps resetting
from 0.00V to actual voltage every 2-3 seconds. Battery is connected directly to BattB pin and GND.
Battery voltage reading from FC is stable and accurate. Here is a short video showing the problem:

[https://www.youtube.com/watch?v=0kmfd04bfhA](url)

**Comment by night-ghost** [comment]
not confirmed - https://youtu.be/y5SQk4_4C6g all works fine (potentiometer between the ground and power supply)
