### ISSUE TITLE
Adjust pin value not as accurate as needed

### ISSUE THREAD

**Issue by Gesiima** [night-ghost/minimosd-extra#164]
Hi, I am trying to attach a APM Power Module directly to my minimOSD like this one.
http://www.banggood.com/APM-Power-Module-V1-Vision-50V-90A-with-BEC-for-RC-Model-p-917309.html
I get values for current and voltage but I am not able to calibrate my messures.
Onboard is a voltage divider 1:10.
For voltage I need a adjust pin value like 10.4 but a dot is not possible.
The value for current is about 18.2Amps per Volt. What is the best way to find out the adjust pin value for that?

**Comment by night-ghost** [comment]
proof?

**Comment by night-ghost** [comment]
>For voltage I need a adjust pin value like 10.4 but a dot is not possible.

really?
![osd](https://cloud.githubusercontent.com/assets/6255710/20244526/dd806076-a9a7-11e6-80a2-657da30c3e4b.png)

**Comment by Gesiima** [comment]
Only triyed dot . not komma , 
Shame on me!
Thanks alot.

**Comment by night-ghost** [comment]
dot or comma is dependent on your locale settings and NET/MONO layer
