### ISSUE TITLE
can not find I2c_soft_slave library

### ISSUE THREAD

**Issue by leomatrix** [night-ghost/minimosd-extra#168]
#### Issue details
_Please describe the problem, or desired feature_

when using git pull update this repository, I find in the 108 line of file of /minimosd-extra/MinimOsd_Extra/Makefile , "ARDUINO_LIBS += I2c_soft_slave" was added, but in the library of repo It can't find I2c_soft_slave .  Do you mean it should be found at arduino's library ???

#### Version
_What version was the issue encountered with_

#### Board type
_What type of the OSD board you are using?_

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[  ] Not applicable
[  ] Not tested

#### TLOG and OSD
_Please provide a links to a relevant screenshot/video, TLOG and OSD files that show the issue_

**Comment by night-ghost** [comment]
yes this feature still not works, just comment out
