### ISSUE TITLE
"TELEMETRY_SPEED" Reduction.

### ISSUE THREAD

**Issue by Theridiidae** [night-ghost/minimosd-extra#170]
#### Issue details
"TELEMETRY_SPEED" Reduction.
#### Version
MinimOsd_Extra_Uni.905DV-MAVLINK-release

#### Board type
MiniOsd

How can I get "MinimOsd_Extra_Uni.905DV-MAVLINK-release.hex" file with a different speed "#define TELEMETRY_SPEED 19200"?
What files should I download for assembly in "the Arduino Ide""?
Sorry my English is bad.

**Comment by night-ghost** [comment]
This version can auto-detect serial port speed so TELEMETRY_SPEED define is needed only to communicate with ConfigTool.

But speed 19200 is to low so that the display of the horizon will be very slow and antsy 

Build via Arduino IDE is not supported, use Makefile instead.
