### ISSUE TITLE
OSD settings pane - uncontrollable

### ISSUE THREAD

**Issue by PaulHam211** [night-ghost/minimosd-extra#173]
#### Issue details
Changing settings through the OSD using stick inputs is not easy, cursor sometimes moves on its own up and down, and also gets stuck changing the value and can overshoot or set a value to zero.

#### Board type
Minimosd

**Comment by night-ghost** [comment]
Just don't use Setup - and no problem

**Comment by PaulHam211** [comment]
Really? I have an issue with a feature, and the resolution is to not use the feature?
