### ISSUE TITLE
TLog Player Controls

### ISSUE THREAD

**Issue by iskess** [night-ghost/minimosd-extra#177]
#### Issue details
The Tlog player resets to the beginning of the tlog each time I make a change to the eeprom.  I have to wait for the takeoff before I can see what I'm looking for. If I could pause the .tlog rather than having it reset to the beginning it would be a lot easier. It would be really nice if there was a fast forward x10 feature like there is in Mission Planner. 

#### Version
Config tool r916

**Comment by night-ghost** [comment]
CT is one-time tool. But PRs are welcome :)

**Comment by pwbecker** [comment]
Perhaps you could edit the tlog, or create your own?

**Comment by night-ghost** [comment]
done, you can skip a part from beginning

**Comment by iskess** [comment]
Thank you!
