### ISSUE TITLE
Request: New panel to indicate when camera is triggering

### ISSUE THREAD

**Issue by iskess** [night-ghost/minimosd-extra#178]
#### Issue details
I would like to be able to see when my mapping camera is triggering. This has already been done here: https://github.com/ArduPilot/ardupilot/pull/1626
Most of us don't have camera feedback setup, but would simply like an indication that the pixhawk is sending out camera triggering signals. 

![image](https://cloud.githubusercontent.com/assets/4913946/23336277/0bce7224-fb6f-11e6-8d03-12ee684f80d3.png)
![image](https://cloud.githubusercontent.com/assets/4913946/23336279/10a7af2c-fb6f-11e6-8020-cc60630bd0d9.png)

**Comment by night-ghost** [comment]
It is unlikely that most users need this feature, but there is paid support for business opportunities

**Comment by night-ghost** [comment]
closed - no answer
