### ISSUE TITLE
time error with negative TZ offset 

### ISSUE THREAD

**Issue by tmaclean** [night-ghost/minimosd-extra#179]
#### Issue details
When I set a timezone offset that shows a time in the prior day, the displayed time is not correct.
E.g. at 2:24 GMT, with offset -4, I see 1090:40 displayed. A small offset like -2 (which is the same day, in this case) displays correctly.

#### Version
v920

#### Board type
CRIUS MinimOSD

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[  ] Not applicable
[x  ] Not tested

#### TLOG and OSD
_Please provide a links to a relevant screenshot/video, TLOG and OSD files that show the issue_

![img_0476](https://cloud.githubusercontent.com/assets/2712345/24130086/f9269a88-0dbc-11e7-8f68-53342855277d.JPG)

**Comment by tmaclean** [comment]
Looks like the time in hours and minutes is stored as a UINT16.  1090 is (64K - 80) / 60 as UINT

**Comment by night-ghost** [comment]
> time in hours and minutes is stored

Sure!

**Comment by night-ghost** [comment]
fixed in v822

**Comment by night-ghost** [comment]
v924
fixed size issue again. Flash is full :(

**Comment by tmaclean** [comment]
Sad to say, MinimOsd_Extra_Uni.924DV-MAVLINK-release is still too big.    :-(

**Comment by night-ghost** [comment]
just download it again

**Comment by tmaclean** [comment]
Good news and bad.  The good is that the file size is better; the bad is that the issue is still there.  At 00:56 GMT, I read 1089:12 on the OSD using time offset -4.

**Comment by night-ghost** [comment]
re-uploaded, plz check again

**Comment by night-ghost** [comment]
silence more than week, closed
