### ISSUE TITLE
When I try to Update Firmare with 9.23 Mavlink it keeps telling me file is to big

### ISSUE THREAD

**Issue by marvinlange** [night-ghost/minimosd-extra#180]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Board type
_What type of the OSD board you are using?_

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[  ] Not applicable
[  ] Not tested

#### TLOG and OSD
_Please provide a links to a relevant screenshot/video, TLOG and OSD files that show the issue_

![img_20170321_191300435 1](https://cloud.githubusercontent.com/assets/17716636/24175147/fe7ecbe6-0e6a-11e7-8c7b-8f02e5ece006.jpg)
![9-23-mavlink](https://cloud.githubusercontent.com/assets/17716636/24175174/22384364-0e6b-11e7-820e-915d73a6315a.jpg)

**Comment by night-ghost** [comment]
v924
fixed size issue again. Flash is full :(

**Comment by marvinlange** [comment]
You are awesome I have been struggling with minimum OSD lack of features for years you have brought it back to life and made it incredibly use-full again !!!!!
GOD Bless You
Marvin
