### ISSUE TITLE
Getting File to Big Isse again is it a winzip issue?

### ISSUE THREAD

**Issue by marvinlange** [night-ghost/minimosd-extra#181]
Mavlink Ver 9.24

![filetobig](https://cloud.githubusercontent.com/assets/17716636/24255158/140cfff4-0fbb-11e7-85c5-b256a395c30b.png)

**Comment by yashm** [comment]
I get the same issue while compiling from source:
![minim](https://cloud.githubusercontent.com/assets/824023/24318372/941d7262-10da-11e7-86fb-efae0d7fc3ce.JPG)

I am trying to compile this for use with the Pixhawk + MAVLINK.
All I've done is added a `#define USE_MAVLINK` in the main file -> MinimOSD_Extra.ino
Thanks!

**Comment by yashm** [comment]
@marvinlange This is still an issue... I still keep getting the same "sketch too big" error when I compile for the 328.
