### ISSUE TITLE
Problem with Pixhawk "Get Params 12"

### ISSUE THREAD

**Issue by mastersurferde** [night-ghost/minimosd-extra#182]
#### Issue details
Hi,
with actual night-ghost Version on MinimOSD I can´t connect to my pixhawks. The OSD has a 4 wire connection. The Mission Planner shows first "Get Params 1" an after collecting the parameters it shows "Get Params 12" an nothing happens until I stop the connection.
I have read from other people having the same problem. I testet on 2 Pixhawks (Quad and Hex with 3.4.6 Firmware) - always the same.
#### Version
I tried different versions. The last version working correct is the 894. Starting with 896 and later the problem happens.

Regards,
Stefan

**Comment by night-ghost** [comment]
All works for me. Proof?

**Comment by mastersurferde** [comment]
Hi,
some minutes ago I did a new test with complete different Equipment:
![img_0284](https://cloud.githubusercontent.com/assets/16389020/24332529/43a720ac-1248-11e7-83dc-9643253869b6.JPG)
Pixhawk 2.4.8 with Arducopter 3.4.6 (my other Tests were made with Pixhawk lite - same result)
MinimOSD from Banggood with actual 924 Mavlink

Trying to connect to pixhawk:
<img width="1920" alt="gettingparam12" src="https://cloud.githubusercontent.com/assets/16389020/24332556/b11f382c-1248-11e7-983b-62fa914f2a58.png">
It doesn´t matter if I try to connect with USB or with 3DR Radio on another serial port - always the same.
https://youtu.be/sIgmMs5Nz7A
MP tries to "Get params 12" until I cancel the action.

The guys here have the same problem:
http://diydrones.com/forum/topics/mission-planner-get-params-12
The first version not working correct, the 986 was released on 11.11.2016. So I think it is the same problem the guys on diydrones have.

I hope, you can help me.
Best regards,
Stefan

**Comment by night-ghost** [comment]
This is very strange, OSD generates HeartBeat but uses IDs that comes from FC.
 Try v925

**Comment by mastersurferde** [comment]
Hi, 
thank you very much, but with 925 I have no overlay. Tried back to 894 - this was ok.
Regards,
Stefan

**Comment by night-ghost** [comment]
>no overlay

fixed in v926

**Comment by mastersurferde** [comment]
Thank you,
actually it works :)
I will do some test in the next days.
Best regards.
