### ISSUE TITLE
Can't show GPS2 values

### ISSUE THREAD

**Issue by mattogodoy** [night-ghost/minimosd-extra#183]
Hello!

I'm trying to display GPS2 in the screen. I have a main GPS and an RTK GPS that is far more accurate.
I'd like to show Latitude, Longitude and Altitude of the second GPS. These values are the ones that you can see as "lat2", "lon2" and "alt2" in Mission Planner.

Is there a way to display those values in the OSD?
Thanks!

**Comment by night-ghost** [comment]
No, this is not available but PRs is welcome!
