### ISSUE TITLE
Comprehensive Explanation of a few Minimosd Config Tool Items

### ISSUE THREAD

**Issue by jwcalvert** [night-ghost/minimosd-extra#185]
#### Issue details
After hours of searching I cannot find any useful explanation of this tool for a few specific items.

#### Version
MinimOSD-Extra Config Tool 2.4.1.5 r916 DV

#### Board type
Two types: MinimOSD (original size) & MinimOSD Micro.  Problems are relevant equally to both.

#### How "canonical" OSD firmware works?
I am using a Taranis Plus, X8R receivers, Pixhawk, & Arduplane V3.7.1
Both boards work fairly well up to a point.  I can get data on many fields in my FPV goggles.
I have provided screen captures in each case.

1) I do not understand how to use of the OSD Toggle Channel Box and its numerous text boxes:
![osd toggle channel](https://cloud.githubusercontent.com/assets/9320299/24673040/ec077910-1944-11e7-8ab9-227c98768b6c.JPG)
What are the by 200 , Once, Rotation Switch,Auti Switch and how to use them?
Can I toggle the screen using something other than CH 8, such as CH 14? How?

2) The Output Box has 3 drop down boxes.  What is each value used for??
![output box](https://cloud.githubusercontent.com/assets/9320299/24673187/6c8c49a8-1945-11e7-84ad-dec887051c17.JPG)
What is being Outputted and to where?

3) I do not understand the sources here and the relationship between this RSSI and the RSSI value I can configure and the Pin #4 RSSI in lower right corner Sensors Box.
![rssi box](https://cloud.githubusercontent.com/assets/9320299/24673272/aa3b7d3c-1945-11e7-8d93-4ced38fb2d3e.JPG)
I can get an RSSI from the Taranis to my Pixhawk from the X8R and into Mission Planner but a value of ZERO shows up in the goggles.

That is it.
Any and all help will be really appreciated as I am burning a lot of hours in trial and error discovery testing which is really painful.

Thanks
Jim Calvert

**Comment by night-ghost** [comment]
This is OpenSource and FREE code, project's WiKi opened for everyone, so those who need documentation - let do fill it. I can use CT without any documentation so "It Works For Me"(C)
