### ISSUE TITLE
Is thier any Reason a Power Distribution Board PDB w/ OSD BEC Output 5V 12V 3A   (Wont Work )

### ISSUE THREAD

**Issue by marvinlange** [night-ghost/minimosd-extra#186]
Below is the Board I Purchased

http://www.ebay.com/itm/Power-Distribution-Board-PDB-w-OSD-BEC-Output-5V-12V-3A-for-CC3C-Naze32-F3-3M/222334012367?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

It lets me upload firmware seems to check out OK but dose  not show data

**Comment by night-ghost** [comment]
I don't have such board so you can treat it as unsupported
