### ISSUE TITLE
OSD randomly shows "No input data"

### ISSUE THREAD

**Issue by M230** [night-ghost/minimosd-extra#187]
#### Issue details
The OSD will show "No input data". Sometimes it will work for a while and then at a random moment switch to the "No input data" screen. Possibly relevant: The current is stuck at 2.0 amps.

#### Version
MinimOsd_Extra_Uni.928DV-MAVLINK-release.hex

#### Board type
MinimOSD v1.1

#### How "canonical" OSD firmware works?
[X] Works fine
[  ] The same bug
[  ] Not applicable
[  ] Not tested
Tested with the latest old minimosd-extra, every now and then it shows "No MAV data" but after a restart it will work.

**Comment by night-ghost** [comment]
video, TLOG and OSD files?

**Comment by night-ghost** [comment]
closed - week without answer
