### ISSUE TITLE
r929 displays no data on screen

### ISSUE THREAD

**Issue by iskess** [night-ghost/minimosd-extra#188]
#### Issue details
r929 displays no data. r928 and earlier work fine with all else being the same. 

#### Version
r929

#### Board type
generic minimOSD

**Comment by night-ghost** [comment]
some bugs in GCC cause such  issues, I need to add some useless calls in Setup() to fix it. Somewhere I got this
![osd](https://cloud.githubusercontent.com/assets/6255710/25069088/0ebf6e9c-2299-11e7-9db7-6e5731332987.png)

somewhere this

![osd](https://cloud.githubusercontent.com/assets/6255710/25069098/4af7a96a-2299-11e7-8d5c-b72c779e700a.png)


just by adding one ''z" to line

`Serial.print_P(PSTR("#1zzzz\n"));`

**Comment by night-ghost** [comment]
number of 'z' guessed in 

v930
* fixed startup hang from v929

now this line is 
`Serial.print_P(PSTR("#1zzzzz\n"));`
