### ISSUE TITLE
WP Distance panel does not work

### ISSUE THREAD

**Issue by iskess** [night-ghost/minimosd-extra#189]
#### Issue details
When navigating to waypoints in Auto mode, the WP Distance panel does not operate. Only the WP label displays. 

#### Version
r928

#### Board type
generic MinimOSD

#### TLOG and OSD

[2017-04-10 15-32-55 (OSD Test Log) .zip](https://github.com/night-ghost/minimosd-extra/files/923948/2017-04-10.15-32-55.OSD.Test.Log.zip)

**Comment by night-ghost** [comment]
.OSD file?

**Comment by iskess** [comment]
[X8 Copter NightGhost.zip](https://github.com/night-ghost/minimosd-extra/files/924185/X8.Copter.NightGhost.zip)

**Comment by night-ghost** [comment]
what is hardware config?

**Comment by iskess** [comment]
Not sure what you are specifically looking for in my hardware config.  
I have a pixhawk connected to a generic MinimOSD using Telem2. When I load the old MinimOSD-Extra r800 the WP Dist panel works fine.

**Comment by iskess** [comment]
Is there any other information I can get for you?

**Comment by iskess** [comment]
@Night-Ghost,
Is there a chance this bug might be fixed by this weekend? I have a big WP mission planned. I know it's free software so I don't mean to be pushy, if you aren't going to be able to get to it I will just have to load up the old r800 and reconfigure. There are just so many other new features I would be missing. 
Thank you for bringing MinimOSD back to life for the community.

**Comment by night-ghost** [comment]
Sure no - my USB hub emitted a magic smoke, new one comes from China by service snails of Russian Post.

**Comment by night-ghost** [comment]
BTW, you still not shows photo/video for this issue

**Comment by iskess** [comment]
![capture](https://cloud.githubusercontent.com/assets/4913946/25685254/fa73acf2-3001-11e7-8727-38abef4fe56b.JPG)
 Here you go.

**Comment by night-ghost** [comment]
should be fixed in v934

**Comment by night-ghost** [comment]
no answer for a week - closed
