### ISSUE TITLE
The maximum time can't more than 60 minutes.

### ISSUE THREAD

**Issue by liminghuang** [night-ghost/minimosd-extra#192]
The maximum time can't more than 60 minutes. Maybe increase the time up to 99 minutes.
thanks.

**Comment by night-ghost** [comment]
proof?

**Comment by liminghuang** [comment]
This issue was forwarded by my friend. I also checked the code, the minute value was always %60.
I think this is why it can't more than 60.

**Comment by night-ghost** [comment]
Issues that are not complied with rules with will not be considered.
