### ISSUE TITLE
OSD_Config.exe enable set value

### ISSUE THREAD

**Issue by PacificBY** [night-ghost/minimosd-extra#198]
#### Issue details
Открываем конфигуратор. Вводим в поле «Sensors/Add» значение «0». Переходим на любое другое поле. Наш нуль заменяется на «1». Причем, такое поведение только со значением «0».

#### Version
OSD_Config.exe 2.4.1.5

**Comment by night-ghost** [comment]
Ok fixed without version change.

**Comment by PacificBY** [comment]
Thanks
