### ISSUE TITLE
Please Update Instructions for Charset Uploads

### ISSUE THREAD

**Issue by rob215x** [night-ghost/minimosd-extra#199]
#### Issue details
First of all, thank you for all of your work on this project!!

Please update the instructions regarding the character set upload. As you know, from version 925 and up, the uploader is no longer part of the firmware but I did not know this and I was getting, "Error entering charset upload mode - invalid data". 

People should know they have to:
1. Upload the Character_Updater_FW.hex to the board
2. Upload the desired character set.
3. Upload the latest regular firmware .hex to the board. 

I did a bit of searching and I could not find anyone explaining this. I eventually found the answer on your ykoctpa.ru support thread but I feel people may not read the changelog and updating the readme.md would be a better solution. 

thanks!

#### Version
v925 and above

#### Board type
MinimOSD Micro

**Comment by night-ghost** [comment]
Which tells us how useful it is to read the changelog :)

corrected
