### ISSUE TITLE
Px4 Pixhawk Flight Modes displayed improperly

### ISSUE THREAD

**Issue by Jesse-Buck** [night-ghost/minimosd-extra#203]
#### Issue details
_Please describe the problem, or desired feature_
Flight Modes are displayed improperly. For example when Acro Mode is active it reads Circ in the flight mode position, Stabilize is Manu, Altitude Hold is Stab, and Loit is Init.
#### Version
_What version was the issue encountered with_
I've used both v880 and v934, both have this problem. However, when I load the OG Minim OSD Extra with 2 screens it reads correctly.

#### Board type
_What type of the OSD board you are using?_
MultiRotorMania Minim OSD.

#### How "canonical" OSD firmware works?
[X] Works fine
[  ] The same bug
[  ] Not applicable
[  ] Not tested

#### TLOG and OSD
_Please provide a links to a relevant screenshot/video, TLOG and OSD files that show the issue_
I'm not sure how to replicate this other than maybe a video showing that the craft is obviously not in a particular mode via flight characteristics.  Maybe a flip in "Circle Mode"? :+1:

**Comment by night-ghost** [comment]
this is user support case, not a bug
