### ISSUE TITLE
Explanation/documentation on Config.h

### ISSUE THREAD

**Issue by pwbecker** [night-ghost/minimosd-extra#206]
#### Issue details
I am trying to recompile the code (using make) and would like to try and reduce the code size by disabling non essential features. (This is to try work around issue #204)

Its not clear what #define's need to be set to get it working on e.g. with APM and MAVLink, and what the function of some of the other #defines are

#### Version
#define VERSION "2.4" 

#### Board type
MinimOSD 328P

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[x ] Not applicable
[  ] Not tested

**Comment by night-ghost** [comment]
Read documntation carefully
