### ISSUE TITLE
MWII roll and pitch angles * 10

### ISSUE THREAD

**Issue by pwbecker** [night-ghost/minimosd-extra#207]
#### Issue details
MWII results in angles being displayed for roll and pitch which are ten times too high

#### Version
938

#### Board type
MinimOSD (329P)

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[ x] Not applicable
[  ] Not tested

#### TLOG and OSD
-

The fix is in protocols/cleanflight_core.h:
 	osd_att.roll = mwii_read_uint(offsetof(MW_ATTITUDE_t, Angle[0]) );
+        osd_att.roll /= 10; // MSP is centidegrees
 	osd_att.pitch  = mwii_read_uint(offsetof(MW_ATTITUDE_t, Angle[1]) );
+        osd_att.pitch /= 10; // MSP is centidegrees

**Comment by night-ghost** [comment]
thanks, will be in next release

**Comment by night-ghost** [comment]
done
