### ISSUE TITLE
can you tell me how to build this project?

### ISSUE THREAD

**Issue by wetouns** [night-ghost/minimosd-extra#208]
I found bug about radar and I know how to fix it,but I don't know how to build this project and use witch IDE to build,can you tell me?

**Comment by wetouns** [comment]
I use Arduino 1.8.4 to build project but the .hex file is 88k,when i use config tool to update fireware it alert "file too big!",what should I do?

**Comment by night-ghost** [comment]
report that bug here

**Comment by pwbecker** [comment]
It doesn't build with the IDE.  There is a .sh build file that can be used.  It may need to be edited for your system, and you may need to edit out some features from Config.h to reduce the code size

**Comment by 0n3-70uch** [comment]
Hi, here is a tutorial for building the code with Linux:
https://www.rcgroups.com/forums/showpost.php?p=35359151&postcount=1266

But it's a bit outdated...

**Comment by night-ghost** [comment]
I just build via 0-BUILD.sh (CentOS 6.5)
