### ISSUE TITLE
OSD Status: Firmware version number not showing update

### ISSUE THREAD

**Issue by pekote** [night-ghost/minimosd-extra#209]
#### Issue details
I tried to update to latest firmw version from Mavlink 926 to 938 but the config tool doesn't update the firmw version in the top. It shows always 926. I then tried to update from 926 to next version 927 and then next ... and so on and everithing updated correctly, the config tool showed each updated version in the top (see attached picture) till i reach version mavlink 933, then it stopped to update the version number for the next version (934), so I decided to go back to version 933.

![2017-09-16_150354](https://user-images.githubusercontent.com/26857620/30514700-97100d54-9af0-11e7-9a55-8414f55e9a99.png)

#### Version
_What version was the issue encountered with_
Version 934 till version 938

#### Board type
_What type of the OSD board you are using?_
Micro minimOSD from HK, I tested 2 different boards, the same issue.

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[  ] Not applicable
[  ] Not tested

#### TLOG and OSD
_Please provide a links to a relevant screenshot/video, TLOG and OSD files that show the issue_

**Comment by night-ghost** [comment]
this is decorative so just ignore this field.

**Comment by pekote** [comment]
Thanks
