### ISSUE TITLE
CharSet Uploading

### ISSUE THREAD

**Issue by bionicbone** [night-ghost/minimosd-extra#210]
#### Issue details
Failed to upload CharSet many times

#### Version
931 & 933 - MavLink Version

#### Board type
MiniOSD

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[  ] Not applicable
[X] Not tested

Changed Wiki Page for the CharSet uploading, seems better to use the firmware Character_Updater_FW.hex   -- Not sure what the "Character_Updater_FW_1.hex" firmware is for ???

Raising issue only to ensure you are happy with the WiKi change

Regards
Kev

**Comment by night-ghost** [comment]
read docs - https://github.com/night-ghost/minimosd-extra/wiki/Charset

**Comment by night-ghost** [comment]
do you read Changelog carefully? 

v925
* font uploader moved out from main firmware. Use Character_Updater_FW.hex instead.
