### ISSUE TITLE
Add option to show GPS coords once per N seconds

### ISSUE THREAD

**Issue by SergeyBokhantsev** [night-ghost/minimosd-extra#214]
#### Issue details
Ususally GPS coordinates on OSD screen are used for rescue reasons in case of crash etc. 
So most of the flight time GPS coordinates are just wasting of screen space.

It would be great to have following options for GPS coord panel:
- always show
- show for one second every 10, 20, 30 seconds

**Comment by night-ghost** [comment]
useless, and lead to aircraft loss in case of crash without coordinates. Moreover blinking text requires much more attention than steady.
