### ISSUE TITLE
FlightMode Displaying Garbage and Not Updating

### ISSUE THREAD

**Issue by CLabeck** [night-ghost/minimosd-extra#228]
#### Issue details
The flightmode is not showing correctly.

The flightmode field permanently displays "M_0". 

It does not show a value that corresponds to a real flight mode (e.g. STAB). 
The shown value does not change when the flight mode on ArduCopter changes.

The field is basically statically displaying the wrong content.

All other fields work perfectly!

#### Version
Using 9.43

#### Board type
DARLC minimOSD (https://www.fpv24.com/dalrc/dalrc-minimosd)

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[  ] Not applicable
[ X ] Not tested (what is canonical?)

#### TLOG and OSD
Screenshot below
![minimosd issue](https://user-images.githubusercontent.com/28509900/40388557-2bfb5896-5e10-11e8-89a7-774b3472fb07.PNG)

**Comment by BondarenkoA** [comment]
Fixed within PR #229

**Comment by night-ghost** [comment]
m_0 means that current mode has code 0. What protocol are you use?
