### ISSUE TITLE
Delta Values & Wrong Flightmode 

### ISSUE THREAD

**Issue by tops4u** [night-ghost/minimosd-extra#230]
#### Issue details
Values like Altitude, Distance, Power Used etc are delta calculated Values instead of decoded Values from the MAVLINK Datastream (where this information is available). 
To proof this, I have a case where there was a short interrupt in the Power Supply (5v) to the OSD during a Mission Flight. 
Check Screenshot just before the Outage:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/6877067/40565428-dc1bd63e-606c-11e8-9d54-f43f09807a42.png">

And afterwards:
<img width="994" alt="ohne titel" src="https://user-images.githubusercontent.com/6877067/40565543-4990d53e-606d-11e8-9419-3e3150ee41aa.png">

As you can see several Values (Altitude!!, Distance flown, Distance to Home, Power Used!!, Flight Time,...) have been reset. Just to note that the Flightmode selected was Mission and not RTL. 

#### Version
R934 MAVLINK PX4

#### Board type
MicrominimOSD

#### How "canonical" OSD firmware works?
[  ] Works fine
[  ] The same bug
[X] Not applicable
[  ] Not tested

**Comment by night-ghost** [comment]
this is feature.

**Comment by tops4u** [comment]
Please don't let me die stupid... what is the use of this?

**Comment by night-ghost** [comment]
MAVlink stream don't contains this data so they are calculated by OSD itself.

**Comment by tops4u** [comment]
Not completely true. Altitude (Above Ground) as well as Current Consumed are available in PX4 Mavlink Stream. I concur that Travel Distance, Distance to Home and Home Alt are not in the Mavlink Stream. However IMHO the vital Flight Data (like ALTITUDE! and a little less the Current Consumed) should always be taken from the stream instead of being calculated by the OSD.

**Comment by night-ghost** [comment]
Really? you could fix it yourself, PRs are welcome.  Did you read a license?
